sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: 0elgeQAJLsI/hWyHPCAsOmosy9w6kJjLizFxxoaWvjijLRCKcrNbub/1GqF/Vq8sfARNkNWEb+4gECPEk/hDdDJCEt/EdvTypc635CnjXVBMzci5tDYvJ7SnEcHbry+tYt/NdLjv8utKYuI687qXiQNqF0nkZ/B2FjaUkm61nJY6lj1nltLhOJeuYKKgC4VzGEf8kU3VR9aFh5eG3EsVOlxi+6CdaGfrErYI+tymGVLT0msBKS9j/36ymz3dc7tRO8uXRyO2znjm3a42v39eKR6tW0u+78So3QKDbTNei2YZkjmy4lRxc0jGjzypS1lVRVCbQGqt3GdJiprn949aRSWpieo0ID85GpzbmlLUf58o5Dd4j/Ow6DrIZCVx2vX6XOhYMvj4vhE04irp+RkEkS6LBFEjKn8i9897PtOQQkNEv+K+dLhCfgcMDbBmp6ZCSJ/FXM0yc4ElT+4k08+PkHgoSh38EQnRp2kMlhuXxDuxcCstv1KANTO8mVZ65xBIWg0My7BCxFVHnYOXH+OSS8QA+D810VbLvJ1dBE0h5AO1H4O843h2VoFjfzj5cRH+HRqFRsznib08yoogPkIy+S8LxehP7YeM0OmGSOYmVx196jlKMIW5aMQLSzzrDKqki7ynPL5k3FvoVyPzGZcPvF8/2U9GqFDD13kFCGWzkW4=
  - secure: FLwYfU/DM9hBYRsjbfsc7t1U5bAmofuoFNGyrBAlSlqYEs6PNOuGS8/qAZkBddKRjesQxmabvS/gVjPr1WP1mP+I6tWIarsMxh8xOcO4aR3JT0vULOorgJ3lmmqpxFm47L9ofPeF76xwWBu3oGJKIhLuDIcqBk9I7hCgN4K9bALHWJg6uC76b2D2HqQ4OAfRcIQ86CWyIZ4IOV7iRKtLZGqgMxdc2A9HHivfzs7Tz/HkPipe84D7qJBmJvNSMXhj30xWuOVuJ3bOAb9gNzzk1YJju4E8Q6Q0J3Fc+rxKD+rWfVNUFCyxvSXRx66NokNLuHv+tt17hAZ9t/Od6u/+tSJMP7GrCAfmYxSN7T88+B/g/r0TTFwpy01jmTF2Ak8xKOXoNXlrXjyTATjEHzU2ZJJqGqpOSWdVqI6m0jQFNevnrCO8+mDlcHeM/WfXq2XzdNkCqCI4SpZ7IwFTFgzURBfgs/OjF9IjdwTnPfPyrUurCrZb5tKzRD6pTgps7+MGfhvEMtqg1mbtsp3a82s+Rk8JQs0OJ9ptcBGGbn2hIlt9volV3IyCS/nh4peH9fm8KEOCliym/7UA0zk3iGNAJUV70zXCArstD+HTMLoTm1K0G2iDbks6NFvCp5+JCRuEQ6fEUOqdK1TE5k9WybE8n1riDnYwGZ3hv+3Ifrpgu/w=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: 0AUQFfS7P2MfLKCK1DCsu61rz8sAdjavkuuZ3RQ2JN6ou9GiE0v5TWWd5uRlr4QGtc7mKfgnyUKInTxBg1Q0GJUZcWMUyhfbGvE36Iafx1TspM5nsPLeaAsqGSEgSjBWcz+//Mf5O6OPr8JS3drSiGrxky5LWmQYXgEP4/wOTwvSx2bR+X3rPmKmoXQJlbHw9DA6RrNzyd2FXJO1Ztkrj80UnjWRWC2q45vGugLEsxp5soVTT+L1G/8PT5bvkaHGCpyKgMOIUQ3jW3gTwld5OZSc9MsxeO0oH2gzD1eJ3U2ritwopNHgXiLdO+j90tlVjrr8sbJf4g/Ll4BxvtVVXSrDKD0x9xsBcNu3DfygI/iEWkKXudi5K/qIz/POAKIxzbrNwzgOXcKHihNooa9c/uAXZEY/8StM8bhYhhGjRMvXLBx/XgN08sHskb+RNmqKR3oJq8gbDVMSgDDpdwX0iLzXuvagraqeeNVmAV7hzCWbnK/oeq6jS4MgPZed9ajTP5Q+o8cALU5UYwB+A0He6B1dF5CoI0BZQUmqGOafWEU++BsrnsYcWrqJ9WOtJ6tW3G+z5GVA9PUQefTNJtH+FpS3xsV8eR2BpTxCcbgRaPJ7MDUnSgxtkz4IqCXlCMMVBMj2wo1rqBgLxS3W3okIhSmUd2SQtj0NccD+iuEx91k=
