version: 2
jobs:
  docs:
    docker:
      - image: p3lim/lua-doc-parser:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:hOrct7MhHISIgTVu6lqnR4nmoNAbmjV+hG0ejsl27HA"
      - checkout
      - run: build
  release:
    docker:
      - image: p3lim/wow-packager:latest
    steps:
      - checkout
      - run: release.sh
workflows:
  version: 2
  docs:
    jobs:
      - docs:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context: api-keys
